# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

vpc_access_connector:
  name: projects/automatic-bond-454109-v8/locations/europe-west6/connectors/database-connector
