# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
manual_scaling:
  instances: 1
resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10
vpc_access_connector:
  name: projects/automatic-bond-454109-v8/locations/europe-west6/connectors/database-connector
env_variables:
  DB_PASSWORD: "${DB_PASSWORD}"