package ch.uzh.ifi.hase.soprafs24.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public record InvitationRequest(
        @JsonProperty("sessionId") long sessionId,
        @JsonProperty("userId") long userId,
        @JsonProperty("senderId") long senderId
        ) {
    // The constructor and getters are automatically generated by the record keyword
    // No need to manually define them
}